Upgrade PHP, Resque and Elasticsearch on docker-1_host and docker-4_hosts containers
QualityUnit/LiveAgent-Docker pull request #6
Opened 2022-02-08 11:26 UTC by msvihra

PR prepare Docker environment and allow to install LA >5.27 which requires these changes.
PR closes https://github.com/QualityUnit/LiveAgent-Docker/issues/5

Docker-4_hosts_2LB need quick individual testing, hence the draft.

2022-02-08 12:16 UTC, msvihra commented
Containers runs fine on `docker-1_host` and also on `docker-4_hosts_2LB` variation. No problems spotted. PR is ready to review.

2022-02-08 12:34 UTC, lubo requested changes

2022-02-08 12:34 UTC, lubo commented on docker-1_host/templates/docker-compose.yml
> +    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
```suggestion
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
```

I believe there's no good reason to not use the latest 7.16. Please, do the same thing everywhere else.

2022-02-08 12:34 UTC, lubo commented on docker-1_host/templates/elasticsearch.yml
> +node.name: "es1-docker-node"
Where did the name come from? What does Docker have to do with this?

2022-02-08 12:34 UTC, lubo commented on docker-1_host/templates/resquev5/Dockerfile
> +ADD https://raw.github.com/QualityUnit/resqu-server/5.4.0/build/php-resque-serial-5.4.0.zip /opt/qu
```suggestion
```

There's no good reason to preserve the archive in the image only for it to be become inaccessible in the next layer.

2022-02-08 12:34 UTC, lubo commented on docker-1_host/templates/resquev5/Dockerfile
> +RUN unzip /opt/qu/php-resque-serial-5.4.0.zip -d /opt/qu/php-resque-5/ && \
```suggestion
RUN curl -O https://raw.github.com/QualityUnit/resqu-server/5.4.0/build/php-resque-serial-5.4.0.zip && \
    echo "d0db7c4e544891dd4a8da949338a34f3d8bc23756f41e162e80f3b97e872a612  php-resque-serial-5.4.0.zip" | sha256sum -c && \
    unzip /opt/qu/php-resque-serial-5.4.0.zip -d /opt/qu/php-resque-5/ && \
```

This makes sure the archive is not left in the image even though it's unlinked later. Also, remote resources must be authenticated. Please, do the same thing everywhere else.

2022-02-08 12:57 UTC, msvihra commented on docker-1_host/templates/elasticsearch.yml
> +node.name: "es1-docker-node"
This is `elasticsearch.yml` and it is using same name as otvher variations. It is used because of ES, which need to have `initial_master` nodes in config file.

2022-02-08 13:13 UTC, msvihra commented on docker-1_host/templates/docker-compose.yml
> +    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
Latest stable version used in https://github.com/QualityUnit/LiveAgent-Docker/pull/6/commits/02a2a4467d699217ef4ab827c163107434e35396

2022-02-08 13:15 UTC, msvihra commented on docker-1_host/templates/resquev5/Dockerfile
> +ADD https://raw.github.com/QualityUnit/resqu-server/5.4.0/build/php-resque-serial-5.4.0.zip /opt/qu
Removed by https://github.com/QualityUnit/LiveAgent-Docker/pull/6/commits/90393f8cd010e7da664106d8f8d3be490b290eba.

2022-02-08 13:32 UTC, lubo commented
Why do I see no changes in [docker-2_hosts](https://github.com/QualityUnit/LiveAgent-Docker/tree/master/docker-2_hosts), [docker-3_hosts](https://github.com/QualityUnit/LiveAgent-Docker/tree/master/docker-3_hosts), [docker-3_hosts_noLB](https://github.com/QualityUnit/LiveAgent-Docker/tree/master/docker-3_hosts_noLB) and [docker-4_hosts](https://github.com/QualityUnit/LiveAgent-Docker/tree/master/docker-4_hosts)? If they're unsupported, then we should probably remove them.

2022-02-08 13:38 UTC, msvihra commented
These variations are unmaintained. I will remove them. Only `docker-1_host` and `docker-4_hosts_2LB` are used.

2022-02-08 14:55 UTC, msvihra commented on docker-1_host/templates/resquev5/Dockerfile
> +RUN unzip /opt/qu/php-resque-serial-5.4.0.zip -d /opt/qu/php-resque-5/ && \
Suggested curl did not work. I believe that you meant to do something like this right - https://github.com/QualityUnit/LiveAgent-Docker/pull/6/commits/69f457453e6c57acb6d7cec7eff0d5db4a73983b ? If yes I will change it everywhere.

2022-02-08 15:22 UTC, lubo commented on docker-1_host/templates/resquev5/Dockerfile
> +    rm -rf /opt/qu/php-resque-serial-5.4.0.zip
```suggestion
RUN cd /opt/qu && \
    VERSION=5.4.0 && \
    curl -fLOsS https://github.com/QualityUnit/resqu-server/raw/${VERSION}/build/php-resque-serial-${VERSION}.zip && \
    echo "d0db7c4e544891dd4a8da949338a34f3d8bc23756f41e162e80f3b97e872a612  php-resque-serial-${VERSION}.zip" | sha256sum -c && \
    unzip php-resque-serial-${VERSION}.zip -d php-resque-5 && \
    rm php-resque-serial-${VERSION}.zip
```

Please, modify it everywhere else too.

2022-02-08 15:24 UTC, lubo commented on docker-1_host/templates/resquev5/Dockerfile
> +RUN unzip /opt/qu/php-resque-serial-5.4.0.zip -d /opt/qu/php-resque-5/ && \
Let's do https://github.com/QualityUnit/LiveAgent-Docker/pull/6/files#r801751867 instead.

2022-02-08 15:26 UTC, msvihra commented on docker-1_host/templates/resquev5/Dockerfile
> +    rm -rf /opt/qu/php-resque-serial-5.4.0.zip
Should not we tie checksum to version? I believe that if we define version like this we should also place checksum there.

2022-02-08 15:51 UTC, lubo commented on docker-1_host/templates/resquev5/Dockerfile
> +    rm -rf /opt/qu/php-resque-serial-5.4.0.zip
Do you mean declaring a variable for the hash too? What's the point if there's just a single occurrence? The hash is fundamentally linked to the version, so I'm unsure of what you mean.

2022-02-08 15:54 UTC, msvihra commented on docker-1_host/templates/resquev5/Dockerfile
> +    rm -rf /opt/qu/php-resque-serial-5.4.0.zip
Yes I meant to declare that this version have this hash. Anyway, it is true that there is only a single occurrence so it is probably not necessary. I will therefore test and change this everywhere.

2022-02-09 08:17 UTC, msvihra commented on docker-1_host/templates/resquev5/Dockerfile
> +    rm -rf /opt/qu/php-resque-serial-5.4.0.zip
Changed everywhere via https://github.com/QualityUnit/LiveAgent-Docker/pull/6/commits/7ad46e3d20927ccbfd28d3d8f77e1641275121b4

2022-02-09 08:26 UTC, msvihra commented on docker-1_host/templates/resquev5/Dockerfile
> +    rm -rf /opt/qu/php-resque-serial-5.4.0.zip
> Please, be so kind and don't close other's discussions.

The discussions was closed after I applied your suggestion. I did not resolved that manually.

2022-02-09 08:33 UTC, msvihra commented
Unused variations removed in https://github.com/QualityUnit/LiveAgent-Docker/pull/6/commits/d757e0753b7ea02c89e55303315035cc54a402da.

2022-02-09 08:43 UTC, lubo commented
Please, squash the related commits, reorder them appropriately, fix commit messages, etc.

2022-02-09 10:19 UTC, msvihra commented
Done. Please see.

2022-02-09 13:58 UTC, lubo approved these changes

2022-02-09 13:59 UTC, merged